enum ConsoleForegroundColor : byte
{
    None        = 00,
    Black       = 30,
    DarkBlue    = 34,
    DarkGreen   = 32,
    DarkCyan    = 36,
    DarkRed     = 31,
    DarkMagenta = 35,
    DarkYellow  = 33,
    Gray        = 37,
    DarkGray    = 90,
    Blue        = 94,
    Green       = 92,
    Cyan        = 96,
    Red         = 91,
    Magenta     = 95,
    Yellow      = 93,
    White       = 97,
}