enum ConsoleBackgroundColor : byte
{
    None        = 0,
    Black       = ConsoleForegroundColor.Black       + 10,
    DarkBlue    = ConsoleForegroundColor.DarkBlue    + 10,
    DarkGreen   = ConsoleForegroundColor.DarkGreen   + 10,
    DarkCyan    = ConsoleForegroundColor.DarkCyan    + 10,
    DarkRed     = ConsoleForegroundColor.DarkRed     + 10,
    DarkMagenta = ConsoleForegroundColor.DarkMagenta + 10,
    DarkYellow  = ConsoleForegroundColor.DarkYellow  + 10,
    Gray        = ConsoleForegroundColor.Gray        + 10,
    DarkGray    = ConsoleForegroundColor.DarkGray    + 10,
    Blue        = ConsoleForegroundColor.Blue        + 10,
    Green       = ConsoleForegroundColor.Green       + 10,
    Cyan        = ConsoleForegroundColor.Cyan        + 10,
    Red         = ConsoleForegroundColor.Red         + 10,
    Magenta     = ConsoleForegroundColor.Magenta     + 10,
    Yellow      = ConsoleForegroundColor.Yellow      + 10,
    White       = ConsoleForegroundColor.White       + 10,
}